language: node_js
node_js:
- '11'
cache:
  directories:
    - node_modules
script:
- npm run test
- npm run build
- npm run coverage
- npm run coveralls
deploy:
- provider: releases
  api_key:
    secure: "Nu3osKPXytpcR4E2Eq8nLBy6cbFd5LRUefOrgUUWsiw8hrt6R+FHXjLGe5w8/HCAeEdXMdJEHu/n1SYkFqNVkMsXfx7n3CAm8mv9MKn+Jtwj4ZDfUc+EysHSznxyRXV++jx2WzOocgGh0x28/ThguX69sSBJlntvcpz9qTTD6gGSNvhreSDMhXz/3OMXawIEHUbl+YvxmDwPktmoJYNWWrhf2aLdxNt1HoMUvhkNbCYy/n0QbINUz3H0ndtdYyJdv1Y0kjvvlqgI41/A6frvWReRmAlnsF2NWnsogXmybRlz9axbk+af46tipChYh3EjQGRwAMn7lZElUi9vfzR94izkDQ0Fwm5AWrVYnN4Jgtk6+7R6BsSjTruW9eYsz5YAok0a5qJvdtydpfDgDBW9omkqj8mPR7gDYqVG3zWAyH4CAq9H5hN8cA4FJ+SeG2il/VKrP/DgIPArYiRRalOnavVfJIQQ8SBnonN+TWyRMV8m/j0/zlGH8VFEhtXvAkqpbnLr7VI7wuGfbMqBiy27r4mHBIFHqMhdiGaUX3z6aQC9dHFaExTOcmGgxnBetcchLzmAGZl8cuM3VKb141brdD3Sxn6Bvxx/KvBiqe+RQW8vA6tpks3QFcqHKXtPQLqHbRv6pLNx5e5sFVTqvRnHLYMHBWYRDhrKFbJG6ngt8SU="
  file: dist/TypetalkCustomEmoji.user.js
  skip_cleanup: true
  on:
    tags: true
- provider: pages
  github-token:
    secure: "ryCpBeAtmxnQ7iVVaAEq2FNmxyPYPPAHzZo++bDE9166chntYn3O0pYbsZk9TqXws+oth38V/SsFzOU7Qkw33kE/wRWzzEPOUCMvfEBLZmhWDoIpFTuv1973U4bbgVqs8E+jCc5BdbUfpW2LtSX4kAUWZXbXwGmwJ0qUSMGK6qdSIiMa8lUFkpZqttNpeAH3iJDNmeSyfm8vGTsJO0C6rIz5Q6n+AeXQSmiX/UWUGVfNU0btu3h+vvSOM03siZHRDYtqvpJOPoRz/SLY+heaR38vICNGZ7/LYwgTzmP7dH4TX9p+cC2imqk43Se1V51dHts5aEoY7W6Jms+81V3KOsnwUzpckHSmXHD00Yv3Z85QNC10cKF2iB8+te9fUVxLlZqkcwJUA5+PaIz8kFX/W0Rsgx0XfCoiYBRd/CnYPrhJalH8W5C977xUep+9PfTat4h8sItnDiNwLmLH7M0QO2JA9Fs8nmkhUKq42F9v+Fv2TX+/NLLO+z5aOwpgbf3z0smHK9Wa1lmyyO85dmGwcmxafv3lFlqAZ2D1gEJ66TyPLsrGovmH5KWy1sAn+76VCD6y1vNRy2ggtwGCRdyz97CZczZARytMThkRKnq6MwEiHbTGRtweNeSogeqRBAVYNiWEW2x7WWj9cwpKfs52jEcqOS/GfY9Xw1Ha6xyP6nY="
  keep-history: true
  skip-cleanup: true
  local-dir: dist/
  on:
    tags: true
